import type { Flag } from "./types";

export const GAME_WIDTH = 480;
export const GAME_HEIGHT = 720;

export const DROP_Y = 100;

export const FLAGS: Flag[] = [
  {
    "id": "cw",
    "code": "cw",
    "name": "Curaçao",
    "color": "#002B7F",
    "rank": 1,
  },
  {
    "id": "ht",
    "code": "ht",
    "name": "Haiti",
    "color": "#00209F",
    "rank": 2,
  },
  {
    "id": "nz",
    "code": "nz",
    "name": "New Zealand",
    "color": "#00008B",
    "rank": 3,
  },
  {
    "id": "uz",
    "code": "uz",
    "name": "Uzbekistan",
    "color": "#00A3E0",
    "rank": 4,
  },
  {
    "id": "jo",
    "code": "jo",
    "name": "Jordan",
    "color": "#1D70B8",
    "rank": 5,
  },
  {
    "id": "cv",
    "code": "cv",
    "name": "Cabo Verde",
    "color": "#002B7F",
    "rank": 6,
  },
  {
    "id": "cd",
    "code": "cd",
    "name": "Congo DR",
    "color": "#007FFF",
    "rank": 7,
  },
  {
    "id": "iq",
    "code": "iq",
    "name": "Iraq",
    "color": "#007A3D",
    "rank": 8,
  },
  {
    "id": "za",
    "code": "za",
    "name": "South Africa",
    "color": "#007A3D",
    "rank": 9,
  },
  {
    "id": "ba",
    "code": "ba",
    "name": "Bosnia & Herz.",
    "color": "#002F6C",
    "rank": 10,
  },
  {
    "id": "qa",
    "code": "qa",
    "name": "Qatar",
    "color": "#8A1538",
    "rank": 11,
  },
  {
    "id": "pa",
    "code": "pa",
    "name": "Panama",
    "color": "#DA1A32",
    "rank": 12,
  },
  {
    "id": "sa",
    "code": "sa",
    "name": "Saudi Arabia",
    "color": "#006C35",
    "rank": 13,
  },
  {
    "id": "gh",
    "code": "gh",
    "name": "Ghana",
    "color": "#FCD116",
    "rank": 14,
  },
  {
    "id": "tn",
    "code": "tn",
    "name": "Tunisia",
    "color": "#E70013",
    "rank": 15,
  },
  {
    "id": "no",
    "code": "no",
    "name": "Norway",
    "color": "#EF2B2D",
    "rank": 16,
  },
  {
    "id": "gb-sct",
    "code": "gb-sct",
    "name": "Scotland",
    "color": "#005EB8",
    "rank": 17,
  },
  {
    "id": "cz",
    "code": "cz",
    "name": "Czechia",
    "color": "#11457E",
    "rank": 18,
  },
  {
    "id": "eg",
    "code": "eg",
    "name": "Egypt",
    "color": "#C0930C",
    "rank": 19,
  },
  {
    "id": "dz",
    "code": "dz",
    "name": "Algeria",
    "color": "#006233",
    "rank": 20,
  },
  {
    "id": "ci",
    "code": "ci",
    "name": "Côte d'Ivoire",
    "color": "#FF8200",
    "rank": 21,
  },
  {
    "id": "ir",
    "code": "ir",
    "name": "IR Iran",
    "color": "#239E46",
    "rank": 22,
  },
  {
    "id": "tr",
    "code": "tr",
    "name": "Türkiye",
    "color": "#E30A17",
    "rank": 23,
  },
  {
    "id": "se",
    "code": "se",
    "name": "Sweden",
    "color": "#006AA7",
    "rank": 24,
  },
  {
    "id": "py",
    "code": "py",
    "name": "Paraguay",
    "color": "#D52B1E",
    "rank": 25,
  },
  {
    "id": "au",
    "code": "au",
    "name": "Australia",
    "color": "#00008B",
    "rank": 26,
  },
  {
    "id": "kr",
    "code": "kr",
    "name": "Korea Republic",
    "color": "#CD2E3A",
    "rank": 27,
  },
  {
    "id": "at",
    "code": "at",
    "name": "Austria",
    "color": "#ED2939",
    "rank": 28,
  },
  {
    "id": "ec",
    "code": "ec",
    "name": "Ecuador",
    "color": "#FFCC00",
    "rank": 29,
  },
  {
    "id": "ca",
    "code": "ca",
    "name": "Canada",
    "color": "#FF0000",
    "rank": 30,
  },
  {
    "id": "sn",
    "code": "sn",
    "name": "Senegal",
    "color": "#11A335",
    "rank": 31,
  },
  {
    "id": "mx",
    "code": "mx",
    "name": "Mexico",
    "color": "#006847",
    "rank": 32,
  },
  {
    "id": "us",
    "code": "us",
    "name": "USA",
    "color": "#002868",
    "rank": 33,
  },
  {
    "id": "co",
    "code": "co",
    "name": "Colombia",
    "color": "#FCD116",
    "rank": 34,
  },
  {
    "id": "ch",
    "code": "ch",
    "name": "Switzerland",
    "color": "#D52B1E",
    "rank": 35,
  },
  {
    "id": "jp",
    "code": "jp",
    "name": "Japan",
    "color": "#00008B",
    "rank": 36,
  },
  {
    "id": "ma",
    "code": "ma",
    "name": "Morocco",
    "color": "#C1272D",
    "rank": 37,
  },
  {
    "id": "uy",
    "code": "uy",
    "name": "Uruguay",
    "color": "#0081C8",
    "rank": 38,
  },
  {
    "id": "hr",
    "code": "hr",
    "name": "Croatia",
    "color": "#FF0000",
    "rank": 39,
  },
  {
    "id": "be",
    "code": "be",
    "name": "Belgium",
    "color": "#E30613",
    "rank": 40,
  },
  {
    "id": "de",
    "code": "de",
    "name": "Germany",
    "color": "#FFCC00",
    "rank": 41,
  },
  {
    "id": "nl",
    "code": "nl",
    "name": "Netherlands",
    "color": "#21468B",
    "rank": 42,
  },
  {
    "id": "pt",
    "code": "pt",
    "name": "Portugal",
    "color": "#FF0000",
    "rank": 43,
  },
  {
    "id": "gb-eng",
    "code": "gb-eng",
    "name": "England",
    "color": "#E21B2C",
    "rank": 44,
  },
  {
    "id": "es",
    "code": "es",
    "name": "Spain",
    "color": "#C60B1E",
    "rank": 45,
  },
  {
    "id": "fr",
    "code": "fr",
    "name": "France",
    "color": "#002395",
    "rank": 46,
  },
  {
    "id": "br",
    "code": "br",
    "name": "Brazil",
    "color": "#009739",
    "rank": 47,
  },
  {
    "id": "ar",
    "code": "ar",
    "name": "Argentina",
    "color": "#75AADB",
    "rank": 48,
  }
];
